# Generated by Django 4.1.13 on 2024-07-19 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_workouts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Workouts",
        ),
    ]
