# Generated by Django 4.1.13 on 2024-07-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
        ("workout", "0002_remove_userworkouthistory_workout_list_workouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="userworkouthistory",
            name="user_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="register.user",
            ),
            preserve_default=False,
        ),
    ]
