# Generated by Django 4.1.13 on 2024-07-22 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout", "0003_userworkouthistory_user_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userworkouthistory",
            name="user",
        ),
    ]
